add spanish language
quark-bot-discord/languages pull request #29
Opened 2024-07-21 14:33 UTC by thedragon40

2024-07-21 14:34 UTC, thedragon40 commented
I have added the Spanish language so that the bot reaches the Spanish community

2024-07-30 11:33 UTC, thatkev requested changes
Please review these changes in order for checks to pass.

2024-07-30 11:33 UTC, thatkev commented on bot/es_es/slash_commands/help.json
> +        "name": "descripción general",
> `descripción general`

This should be combined into one word.

2024-07-30 11:33 UTC, thatkev commented on bot/es_es/slash_commands/help.json
> +        "name": "registro del servidor",
> `registro del servidor`

This should be combined into one word.

2024-07-30 11:33 UTC, thatkev commented on bot/es_es/slash_commands/unban.json
> +        "name": "ID de usuario",
> `ID de usuario`

This should be combined into one word. Should be all lowercase.

2024-07-31 06:29 UTC, thatkev approved these changes

2024-07-31 06:30 UTC, merged